import Head from "next/head"
import MyRecordTemplate from "@/components/Templates/MyRecordTemplate"

export default function Home() {
    return (
        <>
            <Head>
                <title>My Record</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                <MyRecordTemplate />
            </main>
        </>
    )
}
